/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as appAppSubjectIdImport } from './routes/(app)/app.$subjectId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const appAppSubjectIdRoute = appAppSubjectIdImport.update({
  id: '/(app)/app/$subjectId',
  path: '/app/$subjectId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/(app)/app/$subjectId': {
      id: '/(app)/app/$subjectId'
      path: '/app/$subjectId'
      fullPath: '/app/$subjectId'
      preLoaderRoute: typeof appAppSubjectIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app/$subjectId': typeof appAppSubjectIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/$subjectId': typeof appAppSubjectIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/(app)/app/$subjectId': typeof appAppSubjectIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/app/$subjectId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/app/$subjectId'
  id: '__root__' | '/' | '/(app)/app/$subjectId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  appAppSubjectIdRoute: typeof appAppSubjectIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  appAppSubjectIdRoute: appAppSubjectIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/(app)/app/$subjectId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/(app)/app/$subjectId": {
      "filePath": "(app)/app.$subjectId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
