/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as StudyIndexImport } from './routes/study/index'
import { Route as StudySubjectIdImport } from './routes/study/$subjectId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const StudyIndexRoute = StudyIndexImport.update({
  id: '/study/',
  path: '/study/',
  getParentRoute: () => rootRoute,
} as any)

const StudySubjectIdRoute = StudySubjectIdImport.update({
  id: '/study/$subjectId',
  path: '/study/$subjectId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/study/$subjectId': {
      id: '/study/$subjectId'
      path: '/study/$subjectId'
      fullPath: '/study/$subjectId'
      preLoaderRoute: typeof StudySubjectIdImport
      parentRoute: typeof rootRoute
    }
    '/study/': {
      id: '/study/'
      path: '/study'
      fullPath: '/study'
      preLoaderRoute: typeof StudyIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/study/$subjectId': typeof StudySubjectIdRoute
  '/study': typeof StudyIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/study/$subjectId': typeof StudySubjectIdRoute
  '/study': typeof StudyIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/study/$subjectId': typeof StudySubjectIdRoute
  '/study/': typeof StudyIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/study/$subjectId' | '/study'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/study/$subjectId' | '/study'
  id: '__root__' | '/' | '/study/$subjectId' | '/study/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StudySubjectIdRoute: typeof StudySubjectIdRoute
  StudyIndexRoute: typeof StudyIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StudySubjectIdRoute: StudySubjectIdRoute,
  StudyIndexRoute: StudyIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/study/$subjectId",
        "/study/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/study/$subjectId": {
      "filePath": "study/$subjectId.tsx"
    },
    "/study/": {
      "filePath": "study/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
